var path = require('path');
var extractTextPlugin = require('extract-text-webpack-plugin');
var webpack = require("webpack");
var timestampWebpackPlugin = require("timestamp-webpack-plugin");

module.exports = {

    context: path.resolve('src'),

    entry: ["./app.js"],

    output: {
        path: path.resolve('public'),
        publicPath: "/public/",
        filename: "./js/jsBundle.js",
    },

    devServer: {
        contentBase: "src/views"
    },

    plugins: [
        new extractTextPlugin({ // define where to save the file
            filename: './css/cssBundle.css',
            allChunks: true,
        }),
        new webpack.ProvidePlugin({
            $: "jquery",
            Jquery: "jquery",
            "window.Jquery": "jquery"
        }),
        new timestampWebpackPlugin({
            path: __dirname,
            filename: "timestamp.json"
        }),
        new webpack.BannerPlugin("Generated by Webpack Banner Plugin"),
        new webpack.HotModuleReplacementPlugin()

    ],

    module: {
        rules: [
            {
                test: /\.(js|jsx|es6)$/,
                exclude: /node_modules/,
                loader: 'babel-loader'
            },
            {
                test: /\.css$/,
                exclude: /node_modules/,
                loader: extractTextPlugin.extract({
                    fallbackLoader: 'style-loader',
                    loader: 'css-loader!autoprefixer-loader'
                })
            },
            {
                test: /\.scss$/,
                exclude: /node_modules/,
                loader: extractTextPlugin.extract({
                    fallbackLoader: 'style-loader',
                    loader: 'css-loader!autoprefixer-loader!sass-loader'
                })
            },
            {
                test: /\.(png|jpg)$/,
                exclude: /node_modules/,
                loader: 'url-loader?limit=1000'
            }
        ]
    },

    resolve: {
        extensions: ['.js', '.es6', '.jsx','.scss','.css','.json']
    }

}